#   #   #   #   #
# Set occupied on Homeassistant start
  - alias: 'Home Assistant home variable on start'
    trigger:
        platform: homeassistant
        event: start
    condition:
        condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
        service: input_boolean.turn_on
        entity_id: input_boolean.home
        
# Parents on Homeassistant start
  - alias: 'Home Assistant parents variable on start'
    trigger:
        platform: homeassistant
        event: start
    condition:
        condition: state
        entity_id: group.parents
        state: 'home'
    action:
        service: input_boolean.turn_on
        entity_id: input_boolean.parents

# Someone home, set home variable
  - alias: 'Home occupied'
    trigger:
      - platform: state
        entity_id: device_tracker.iphone_aaron
        to: 'home'
      - platform: state
        entity_id: device_tracker.iphone_shawn
        to: 'home'
      - platform: state
        entity_id: device_tracker.iphone_chris
        to: 'home'
      - platform: state
        entity_id: device_tracker.iphone_sherri
        to: 'home'
    action:
        service: input_boolean.turn_on
        entity_id: input_boolean.home

# Everyone gone, set home variable
  - alias: 'Home empty'
    trigger:
      - platform: state
        entity_id: group.all_devices
        to: 'not_home'
    action:
        service: input_boolean.turn_off
        entity_id: input_boolean.home

# Parents here, set parents variable
  - alias: 'Parents home'
    trigger:
      - platform: state
        entity_id: device_tracker.iphone_chris
        to: 'home'
      - platform: state
        entity_id: device_tracker.iphone_sherri
        to: 'home'
    action:
        service: input_boolean.turn_on
        entity_id: input_boolean.parents

# Parents gone, set parents variable
  - alias: "Parents gone"
    trigger:
       - platform: state
         entity_id: group.parents
         to: 'not_home'
    action:
        service: input_boolean.turn_off
        entity_id: input_boolean.parents
        
# Turns on lights if people are home
  - alias: 'Lights on arrival'
    trigger:
      - platform: state
        entity_id: input_boolean.home
        from: 'off'
        to: 'on'
    condition:
        condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.parents
                state: 'on'
              - condition: time
                before: '22:00:00'
          - condition: state
            entity_id: input_boolean.parents
            state: 'off'
    action:
        service: scene.turn_on
        entity_id: scene.turn_on_livingroom

# Turn on bedroom lights when Aaron arrives
  - alias: 'Bedroom lights on for Aaron'
    trigger:
        platform: state
        entity_id: device_tracker.iphone_aaron
        to: 'home'
    action:
        service: scene.turn_on
        entity_id: scene.turn_on_bedroom
        
# Turn off lights when everybody leaves the house
  - alias: 'Lights off when away'
    trigger:
      - platform: state
        entity_id: input_boolean.home
        to: 'off'
    action:
        service: scene.turn_on
        entity_id: scene.turn_off_all  

# Shield lights      
  - alias: "Media player paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.shield_android_tv
        from: 'playing'
    condition:
        condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.parents
                state: 'on'
              - condition: time
                before: '22:00:00'
          - condition: state
            entity_id: input_boolean.parents
            state: 'off'
          - condition: state
            entity_id: light.living_room
            state: 'on'
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_normal

  - alias: "Media player playing"
    trigger:
      - platform: state
        entity_id: media_player.shield_android_tv
        to: 'playing'
    condition:
        condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.parents
                state: 'on'
              - condition: time
                before: '22:00:00'
          - condition: state
            entity_id: input_boolean.parents
            state: 'off'
          - condition: state
            entity_id: light.living_room
            state: 'on'
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_dim      

# Turn off lights when parents here
  - alias: "Turn off lights when parents here at 10PM"
    trigger:
        platform: time
        at: '22:00:00'
    condition:
        condition: and
        conditions:
          - condition: state
            entity_id: light.living_room
            state: 'on'
          - condition: state
            entity_id: input_boolean.parents
            state: 'on'
    action:
        service: scene.turn_on
        entity_id: scene.turn_off_livingroom 
        
# Turn off all lights at 3AM Daily
  - alias: "Turn off lights at 3AM"
    trigger:
        platform: time
        at: '03:00:00'
    action:
        service: scene.turn_on
        entity_id: scene.turn_off_all

# Turn off bedroom at 2AM T-F
  - alias: "Turn off bedroom lamp T-F"
    trigger:
      - platform: time
        at: '02:00:00'
    condition:
      - condition: time
        weekday:
          - tue
          - wed
          - thu
          - fri
    action:
        service: scene.turn_on
        entity_id: scene.turn_off_bedroom

# Turn off bedroom at 10:30 Friday
  - alias: "Turn off bedroom lamp Friday"
    trigger:
      - platform: time
        at: '22:30:00'
    condition:
      - condition: time
        weekday: fri
    action:
        service: scene.turn_on
        entity_id: scene.turn_off_bedroom

# Turn on bedroom lamp to wake up        
  - alias: "Turn on bedroom lamp in the morning T-F"
    trigger:
        platform: time
        at: '10:00:00'
    condition:
        condition: time
        weekday:
          - tue
          - wed
          - thu
          - fri
    action:
        service: scene.turn_on
        entity_id: scene.turn_on_bedroom
  - alias: "Turn on bedroom lamp Saturday morning"
    trigger:
        platform: time
        at: '07:00:00'
    condition:
        condition: time
        weekday: sat
    action:
        service: scene.turn_on
        entity_id: scene.turn_on_all
        
# Turn off bedroom when Aaron leaves
  - alias: "Turn off bedroom when Aaron leaves"
    trigger:
        platform: state
        entity_id: device_tracker.iphone_aaron
        to: 'not_home'
    action:
        service: scene.turn_on
        entity_id: scene.turn_off_bedroom
        
# Turn on night lights when parents not here, motion in living room
  - alias: "Night lights, no parents"
    trigger:
        platform: state
        entity_id: group.occupancy
        to: "on"
    condition:
        condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.parents
            state: 'off'
          - condition: state
            entity_id: group.all_lights
            state: 'off'
          - condition: state
            entity_id: input_boolean.home
            state: 'on'
    action:
        service: scene.turn_on
        entity_id: scene.turn_on_nightlight

# Turn off nightlight after 10 minutes of no detection
  - alias: "Night lights turn off, no parents"
    trigger:
        platform: state
        entity_id: group.occupancy
        to: "off"
        for:
            minutes: 10
    condition:
        condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.parents
            state: 'off'
          - condition: state
            entity_id: group.dining
            state: 'on'
          - condition: state
            entity_id: input_boolean.home
            state: 'on'
    action:
        service: scene.turn_on
        entity_id: scene.turn_off_nightlight        
# Turn on lights when home, and nighttime
  - alias: "Lights on when home, on sundown"
    trigger:
        platform: sun
        event: sunset
        offset: "-00:45:00"
    condition:
        condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.home
            state: 'on'
          - condition: state
            entity_id: group.all_lights
            state: 'off'
    action:
        service: scene.turn_on
        entity_id: scene.turn_on_all
        
        
